"""Generate js/data/problems.js (NeetCode 150) and js/data/bonus.js from NeetCode's official problem list.

Run: python tools/build_problems.py
"""
import json
import pathlib
import urllib.request

SOURCE = "https://raw.githubusercontent.com/neetcode-gh/leetcode/main/.problemSiteData.json"
DATA_DIR = pathlib.Path(__file__).resolve().parent.parent / "js" / "data"
OUT = DATA_DIR / "problems.js"
BONUS_OUT = DATA_DIR / "bonus.js"
BONUS_PER_TOPIC = 6
BONUS_DIFFICULTY_ORDER = {"Medium": 0, "Hard": 1, "Easy": 2}

TOPIC_ORDER = [
    "Arrays & Hashing",
    "Two Pointers",
    "Sliding Window",
    "Stack",
    "Binary Search",
    "Linked List",
    "Trees",
    "Tries",
    "Heap / Priority Queue",
    "Backtracking",
    "Graphs",
    "Advanced Graphs",
    "1-D Dynamic Programming",
    "2-D Dynamic Programming",
    "Greedy",
    "Intervals",
    "Math & Geometry",
    "Bit Manipulation",
]
DIFFICULTY_ORDER = {"Easy": 0, "Medium": 1, "Hard": 2}


def to_record(p):
    return {
        "id": p["code"],
        "title": p["problem"],
        "topic": p["pattern"],
        "slug": p["link"].strip("/"),
        "video": p.get("video") or "",
        "difficulty": p["difficulty"],
        "blind75": bool(p.get("blind75")),
    }


def write_js(path, var, records):
    body = json.dumps(records, indent=1, ensure_ascii=False)
    path.write_text(
        "// Generated by tools/build_problems.py from neetcode-gh/leetcode. Do not edit by hand.\n"
        "(function (root) {\n"
        f"  var {var} = {body};\n"
        f"  if (typeof module !== 'undefined') module.exports = {var};\n"
        f"  else root.{var} = {var};\n"
        "})(this);\n",
        encoding="utf-8",
    )
    print(f"wrote {len(records)} records to {path}")


def main():
    raw = json.loads(urllib.request.urlopen(SOURCE, timeout=30).read())
    indexed = [t for t in enumerate(raw) if t[1].get("neetcode150")]
    indexed.sort(key=lambda t: (
        TOPIC_ORDER.index(t[1]["pattern"]),
        DIFFICULTY_ORDER[t[1]["difficulty"]],
        t[0],
    ))

    bonus = []
    for topic in TOPIC_ORDER:
        pool = [t for t in enumerate(raw)
                if t[1]["pattern"] == topic and not t[1].get("neetcode150")
                and not t[1].get("premium") and t[1].get("video")]
        pool.sort(key=lambda t: (BONUS_DIFFICULTY_ORDER[t[1]["difficulty"]], t[0]))
        bonus.extend(to_record(p) for _, p in pool[:BONUS_PER_TOPIC])

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    write_js(OUT, "PROBLEMS", [to_record(p) for _, p in indexed])
    write_js(BONUS_OUT, "BONUS", bonus)


if __name__ == "__main__":
    main()
