"""Generate js/data/problems.js from NeetCode's official problem list.

Run: python tools/build_problems.py
"""
import json
import pathlib
import urllib.request

SOURCE = "https://raw.githubusercontent.com/neetcode-gh/leetcode/main/.problemSiteData.json"
OUT = pathlib.Path(__file__).resolve().parent.parent / "js" / "data" / "problems.js"

TOPIC_ORDER = [
    "Arrays & Hashing",
    "Two Pointers",
    "Sliding Window",
    "Stack",
    "Binary Search",
    "Linked List",
    "Trees",
    "Tries",
    "Heap / Priority Queue",
    "Backtracking",
    "Graphs",
    "Advanced Graphs",
    "1-D Dynamic Programming",
    "2-D Dynamic Programming",
    "Greedy",
    "Intervals",
    "Math & Geometry",
    "Bit Manipulation",
]
DIFFICULTY_ORDER = {"Easy": 0, "Medium": 1, "Hard": 2}


def main():
    raw = json.loads(urllib.request.urlopen(SOURCE, timeout=30).read())
    items = [p for p in raw if p.get("neetcode150")]
    indexed = list(enumerate(items))
    indexed.sort(key=lambda t: (
        TOPIC_ORDER.index(t[1]["pattern"]),
        DIFFICULTY_ORDER[t[1]["difficulty"]],
        t[0],
    ))
    problems = [{
        "id": p["code"],
        "title": p["problem"],
        "topic": p["pattern"],
        "slug": p["link"].strip("/"),
        "video": p.get("video") or "",
        "difficulty": p["difficulty"],
        "blind75": bool(p.get("blind75")),
    } for _, p in indexed]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(problems, indent=1, ensure_ascii=False)
    OUT.write_text(
        "// Generated by tools/build_problems.py from neetcode-gh/leetcode. Do not edit by hand.\n"
        "(function (root) {\n"
        f"  var PROBLEMS = {body};\n"
        "  if (typeof module !== 'undefined') module.exports = PROBLEMS;\n"
        "  else root.PROBLEMS = PROBLEMS;\n"
        "})(this);\n",
        encoding="utf-8",
    )
    print(f"wrote {len(problems)} problems to {OUT}")


if __name__ == "__main__":
    main()
